language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "yashsharma205@gmail.com"